APOSTROPHE = "'";
BRACE_CLOSE = "}";
BRACE_OPEN = "{";
COMMA = ",";
DOUBLE_QUOTE = "\"";
DOT = "."
EQUAL = "="
LESS = "<"
MORE = ">"
ROUND_PARENTHESIS_CLOSE = ")"
ROUND_PARENTHESIS_OPEN = "("
SQUARE_BRACKET_CLOSE = "]"
SQUARE_BRACKET_OPEN = "[";
UTF_8 = "utf-8"



XML_EXTENSION = 'xml'
